# condition is checked first, then task executed.
---
- name: Provisioning server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP on Centos
      yum:
         name: "{{item}}"
         state: present
      when: ansible_distribution == "CentOS"
# loops is used to execute task multiple times for everything that is listed under loop. Loop variable is {{item}}   
      loop:
        - ntp
        - wget
        - git
        - zip
    
    - name: Install NTP on ubuntu
      apt:
         name: "{{item}}"
         state: present
# this will run apt-update first         
         update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip

    - name: Start and enable NTP on Redhat
      service:
         name: ntpd
         state: started
         enabled: yes
      when: ansible_os_family == "RedHat" 
    
    - name: Start and enable NTP on Debian
      service:
         name: ntp
         state: started
         enabled: yes
      when: ansible_os_family == "Debian"     

    - name: Add group
      group:
        name: devops
        state: present

    - name: Add users
      user:
        name: "{{item}}"
        state: present
        groups: devops
      loop:
        - user1
        - user2
        - user3

# add motd message
    - name: Banner file /etc/motd
      copy:
        content: "This {{ansible_distribution}} system is managed by ansible \n"
        dest: /etc/motd

# create directory. Using 'File' module
    - name: Dir for dev data
      file:
        path: /opt/devdata
        state: directory
        mode: 0775
